services:
  - type: web
    name: sharemeal-api
    runtime: node
    region: oregon
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    preDeployCommand: npm run migrate
    autoDeployTrigger: commit
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3000
      - key: DB_PORT
        value: 3306
    plan: starter
    numInstances: 1
